# environment.yml

name: trch
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - asttokens=3.0.0=pyhd8ed1ab_1
  - ca-certificates=2025.4.26=h4c7d964_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - cpython=3.9.22=py39hd8ed1ab_1
  - debugpy=1.8.14=py39ha51f57c_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ipykernel=6.29.5=pyh4bbf305_0
  - ipython=8.18.1=pyh7428d3b_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh5737063_1
  - krb5=1.21.3=hdf4eb48_0
  - libsodium=1.0.20=hc70643c_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.0=ha4e3fda_1
  - parso=0.8.4=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=24.2=py39haa95532_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py39ha55e580_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.1=pyhd8ed1ab_0
  - python=3.9.21=h8205438_1
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python_abi=3.9=2_cp39
  - pyzmq=26.4.0=py39h03e5c00_0
  - six=1.17.0=pyhd8ed1ab_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tornado=6.5=py39ha55e580_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.13.2=pyh29332c3_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34438=hfd919c2_26
  - vs2015_runtime=14.42.34438=h7142326_26
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wincertstore=0.2=py39haa95532_2
  - zeromq=4.3.5=ha9f60a1_7
  - zipp=3.21.0=pyhd8ed1ab_1
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.10.11
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.7
      - annotated-types==0.7.0
      - anyio==4.8.0
      - appdirs==1.4.4
      - argcomplete==3.5.3
      - arrow==1.3.0
      - asgiref==3.8.1
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attr==0.3.1
      - attrs==24.3.0
      - azure-core==1.32.0
      - azure-storage-blob==12.24.0
      - backoff==2.2.1
      - bing-image-downloader==1.1.2
      - black==24.10.0
      - bleach==5.0.1
      - boto==2.49.0
      - boto3==1.36.2
      - botocore==1.36.2
      - cachetools==5.5.0
      - certifi==2024.12.14
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - codecarbon==3.0.1
      - commonmark==0.9.1
      - contourpy==1.3.0
      - cryptography==44.0.0
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datamodel-code-generator==0.26.1
      - deep-sort-realtime==1.3.2
      - defusedxml==0.7.1
      - deprecated==1.2.15
      - distro==1.9.0
      - django==4.2.18
      - django-annoying==0.10.6
      - django-cors-headers==3.6.0
      - django-csp==3.7
      - django-debug-toolbar==3.2.1
      - django-environ==0.10.0
      - django-extensions==3.2.3
      - django-filter==2.4.0
      - django-migration-linter==5.1.0
      - django-model-utils==4.1.1
      - django-ranged-fileresponse==0.1.2
      - django-rq==2.5.1
      - django-storages==1.12.3
      - django-user-agents==0.4.0
      - djangorestframework==3.15.2
      - dnspython==2.7.0
      - docker==7.1.0
      - drf-dynamic-fields==0.3.0
      - drf-flex-fields==0.9.5
      - drf-generators==0.3.0
      - efficientnet-pytorch==0.7.1
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - expiringdict==1.2.2
      - faker==33.3.1
      - fief-client==0.20.0
      - filelock==3.13.1
      - filetype==1.2.0
      - flatbuffers==24.12.23
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - gast==0.6.0
      - genson==1.3.0
      - google-api-core==2.24.0
      - google-auth==2.37.0
      - google-cloud-appengine-logging==1.5.0
      - google-cloud-audit-log==0.3.0
      - google-cloud-core==2.4.1
      - google-cloud-logging==3.11.3
      - google-cloud-storage==2.19.0
      - google-crc32c==1.6.0
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.66.0
      - grpc-google-iam-v1==0.14.0
      - grpcio==1.69.0
      - grpcio-status==1.69.0
      - h11==0.14.0
      - h5py==3.12.1
      - httpcore==1.0.7
      - httpx==0.27.2
      - huggingface-hub==0.31.4
      - humansignal-drf-yasg==1.21.10.post1
      - idna==3.7
      - ijson==3.3.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - inference-cli==0.46.5
      - inflect==5.6.2
      - inflection==0.5.1
      - isodate==0.7.2
      - isort==5.13.2
      - jinja2==3.1.3
      - jiter==0.8.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsf==0.11.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jwcrypto==1.5.6
      - kagglehub==0.3.11
      - keras==3.8.0
      - kiwisolver==1.4.7
      - label-studio==1.15.0
      - label-studio-sdk==1.0.8
      - lap==0.5.12
      - launchdarkly-server-sdk==8.2.1
      - libclang==18.1.1
      - lockfile==0.12.2
      - lxml==5.3.0
      - lxml-html-clean==0.4.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.26.1
      - matplotlib==3.9.4
      - mdurl==0.1.2
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - multidict==6.4.3
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - networkx==3.2.1
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - openai==1.59.8
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.29.0
      - opt-einsum==3.4.0
      - optree==0.14.0
      - ordered-set==4.0.2
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==10.2.0
      - pillow-heif==0.22.0
      - platformdirs==4.3.6
      - prometheus-client==0.22.0
      - propcache==0.3.1
      - proto-plus==1.25.0
      - protobuf==5.29.4
      - psycopg2-binary==2.9.10
      - py-cpuinfo==9.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybase64==1.0.2
      - pyboxen==1.3.0
      - pycparser==2.22
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - pyrfc3339==2.0.1
      - python-dotenv==1.1.0
      - python-json-logger==2.0.4
      - pytz==2022.7.1
      - pywin32==310
      - pyyaml==6.0.2
      - questionary==2.1.0
      - rapidfuzz==3.13.0
      - redis==3.5.3
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-mock==1.12.1
      - requests-toolbelt==1.0.0
      - rich==13.0.1
      - roboflow==1.1.61
      - rpds-py==0.22.3
      - rq==1.10.1
      - rsa==4.9
      - rstr==3.2.2
      - rules==3.4
      - s3transfer==0.11.1
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semver==3.0.3
      - sentence-transformers==4.1.0
      - sentry-sdk==2.20.0
      - setuptools==80.3.1
      - shapely==2.0.7
      - shellingham==1.5.4
      - simsimd==6.2.1
      - smart-open==7.1.0
      - sniffio==1.3.1
      - sqlparse==0.5.3
      - stringzilla==3.12.5
      - supervision==0.25.1
      - sympy==1.13.3
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-intel==2.18.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==2.3.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tqdm==4.67.1
      - transformers==4.52.1
      - typer==0.12.5
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - ua-parser==1.0.0
      - ua-parser-builtins==0.18.0.post1
      - ujson==5.10.0
      - ultralytics==8.3.107
      - ultralytics-thop==2.0.14
      - uritemplate==4.1.1
      - urllib3==1.26.20
      - user-agents==2.2.0
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wheel==0.40.0
      - wrapt==1.17.2
      - xmljson==0.2.1
      - yarl==1.19.0
      - yaspin==3.1.0
prefix: C:\Users\Piko\anaconda3\envs\trch
